
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    joda-date-time-format: yyyy-MM-dd HH:mm:ss.SSS
  http: 
    multipart: 
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss.SSS

app:
  file-directory: d:/
  file-path-format: yyyy/MM/dd/
  file-name-format: yyyyMMddHHmmssSSS
  file-uri-prefix: https://baobeidaodao.com/